services:
  - type: web
    name: innovation-hub-api
    runtime: java
    repo: https://github.com/ishimweolivier-coder/Innovation_hub_project
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/innovation-hub-api-1.0.0.jar
    envVars:
      - key: PGUSER
        fromDatabase:
          name: innovation-hub-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: innovation-hub-db
          property: password
      - key: PGHOST
        fromDatabase:
          name: innovation-hub-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: innovation-hub-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: innovation-hub-db
          property: database
      - key: MAIL_USERNAME
        value: olivierishimwe006@gmail.com
      - key: MAIL_PASSWORD
        value: bhqxobrabiplgeus
      - key: JWT_SECRET
        value: InnovationHubRwSecretKey2026MustBeAtLeast256BitsLongForHS256Algorithm!!

databases:
  - name: innovation-hub-db
    databaseName: innovation_hub
    user: postgres
