export function getScoringLabel(engineVersion, aiStatus) {
  if (engineVersion?.startsWith('openai')) {
    return {
      short: 'AI Analysis',
      long: `AI Document Analysis (${engineVersion.replace('openai-', '')})`,
      description: 'OpenAI reads your uploaded business plan and budget to produce scores and a written summary.',
    }
  }

  if (aiStatus?.openAiConfigured) {
    return {
      short: 'Automated Scoring',
      long: 'Automated Scoring',
      description: 'Rule-based scoring using your application data and extracted document text.',
    }
  }

  return {
    short: 'Automated Scoring',
    long: aiStatus?.label || 'Automated Scoring',
    description: aiStatus?.description
      || 'Scores are generated by our automated scoring engine from your application and uploaded documents. Set OPENAI_API_KEY on the server for full AI document analysis.',
  }
}

export function isProjectionMetric(metric) {
  return metric?.isProjection === true || metric?.month === 'Projected'
}
